#!/usr/bin/env bash
LC_ALL=C
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
source /usr/bin/variables

yad --center --text-align=fill --borders=6 --title="Swapfile Scan" --button="Crear archivo swap":0 --button="Buscar archivos swap":1 --button="Seleccionar la ubicacion del archivo swap":2 --button="Salir":3 --text="Seleccione la accion que desea realizar"

mode="$?"

case $mode in
	0)
		$advertencia --text="Seleccione la carpeta donde desea crear el archivo swap."
		ubicacion=(yad --file-selection --height 380 --width 500)
		dd if=/dev/zero of="$ubicacion"/swapfile.swp bs=1024 count=102400
		chown root:root "$ubicacion"/swapfile.swp
		chmod 0600 "$ubicacion"/swapfile.swp
		mkswap "$ubicacion"/swapfile.swp
		$final --text="Finalizado."
		;;

	1)
		contar=0
		for i in $(find /media/user/ -type f -name "swapfile.swp"); do
			let contar=$(($contar+1))
			losetup /dev/loop$contar $i
			mkswap /dev/loop$contar
			swapon -p 30 -f /dev/loop$contar
		done
		$final --text="Finalizado."
		;;

	2)
		dispositivo3=(yad --file-selection --height 380 --width 500)
		losetup /dev/loop9 $dispositivo3
		mkswap /dev/loop9
		swapon -p 30 -f /dev/loop9
		$final --text="Finalizado."
		;;

	3)
		rm -f /run/$(basename $0).pid
		exit 0
		;;

esac
rm -f /run/$(basename $0).pid
exit 0
