#!/usr/bin/env bash
LC_ALL=C
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
source /usr/bin/variables

yad --center --text-align=fill --borders=6 --title="Swapfile Scan" --button="Crear archivo swap":0 --button="Buscar archivos swap":1 --button="Seleccionar la ubicacion del archivo swap":2 --button="Salir":3 --text="Seleccione la accion que desea realizar"

mode="$?"

case $mode in
	0)
		dispositivo=$(fdisk -l | grep "Disco" | grep -v "loop" | grep -v "zram" | awk '{print $2}' | sed 's/.$//g' | yad --center --no-click --list --title="Seleccione dispositivo" --text="Seleccione el dispositivo donde desea crear el archivo swap." --separator="" --column 'Dispositivo' --height 380 --width 150 --button="ACEPTAR":0)
		dispositivo2=$(fdisk -l "dispositivo" | grep "/dev/" | grep -v "Disco" | awk '{print $1}' | yad --center --no-click --list --title="Seleccione la particion" --text="Seleccione la particion donde desea crear el archivo swap." --separator="" --column 'Dispositivo' --height 380 --width 150 --button="ACEPTAR":0)
		dd if=/dev/zero of="$dispositivo2"/swapfile.swp bs=1024 count=102400
		chown root:root "$dispositivo2"/swapfile.swp
		chmod 0600 "$dispositivo2"/swapfile.swp
		mkswap "$dispositivo2"/swapfile.swp
		$final --text="Finalizado."
		;;

	1)
		contar=0
		for i in $(find /media/user/ -type f -name "swapfile.swp"); do
			let contar=$(($contar+1))
			losetup /dev/loop$contar $i
			mkswap /dev/loop$contar
			swapon -p 30 -f /dev/loop$contar
		done
		$final --text="Finalizado."
		;;

	2)
		dispositivo3=(yad --file-selection --height 380 --width 500)
		losetup /dev/loop9 $dispositivo3
		mkswap /dev/loop9
		swapon -p 30 -f /dev/loop9
		$final --text="Finalizado."
		;;

	3)
		rm -f /run/$(basename $0).pid
		exit 0
		;;

esac
rm -f /run/$(basename $0).pid
exit 0
